// Code generated by ent, DO NOT EDIT.

package directmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the directmessage type in the database.
	Label = "direct_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUser1ID holds the string denoting the user1_id field in the database.
	FieldUser1ID = "user1_id"
	// FieldUser2ID holds the string denoting the user2_id field in the database.
	FieldUser2ID = "user2_id"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser1 holds the string denoting the user1 edge name in mutations.
	EdgeUser1 = "user1"
	// EdgeUser2 holds the string denoting the user2 edge name in mutations.
	EdgeUser2 = "user2"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the directmessage in the database.
	Table = "direct_messages"
	// User1Table is the table that holds the user1 relation/edge.
	User1Table = "direct_messages"
	// User1InverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	User1InverseTable = "users"
	// User1Column is the table column denoting the user1 relation/edge.
	User1Column = "user1_id"
	// User2Table is the table that holds the user2 relation/edge.
	User2Table = "direct_messages"
	// User2InverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	User2InverseTable = "users"
	// User2Column is the table column denoting the user2 relation/edge.
	User2Column = "user2_id"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "direct_message_contents"
	// MessagesInverseTable is the table name for the DirectMessageContent entity.
	// It exists in this package in order to avoid circular dependency with the "directmessagecontent" package.
	MessagesInverseTable = "direct_message_contents"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "direct_message_messages"
)

// Columns holds all SQL columns for directmessage fields.
var Columns = []string{
	FieldID,
	FieldUser1ID,
	FieldUser2ID,
	FieldLastMessageAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DirectMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUser1ID orders the results by the user1_id field.
func ByUser1ID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUser1ID, opts...).ToFunc()
}

// ByUser2ID orders the results by the user2_id field.
func ByUser2ID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUser2ID, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUser1Field orders the results by user1 field.
func ByUser1Field(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUser1Step(), sql.OrderByField(field, opts...))
	}
}

// ByUser2Field orders the results by user2 field.
func ByUser2Field(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUser2Step(), sql.OrderByField(field, opts...))
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUser1Step() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(User1InverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, User1Table, User1Column),
	)
}
func newUser2Step() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(User2InverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, User2Table, User2Column),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
