// Code generated by ent, DO NOT EDIT.

package directmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldID, id))
}

// User1ID applies equality check predicate on the "user1_id" field. It's identical to User1IDEQ.
func User1ID(v int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldUser1ID, v))
}

// User2ID applies equality check predicate on the "user2_id" field. It's identical to User2IDEQ.
func User2ID(v int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldUser2ID, v))
}

// LastMessageAt applies equality check predicate on the "last_message_at" field. It's identical to LastMessageAtEQ.
func LastMessageAt(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldLastMessageAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// User1IDEQ applies the EQ predicate on the "user1_id" field.
func User1IDEQ(v int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldUser1ID, v))
}

// User1IDNEQ applies the NEQ predicate on the "user1_id" field.
func User1IDNEQ(v int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldUser1ID, v))
}

// User1IDIn applies the In predicate on the "user1_id" field.
func User1IDIn(vs ...int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldUser1ID, vs...))
}

// User1IDNotIn applies the NotIn predicate on the "user1_id" field.
func User1IDNotIn(vs ...int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldUser1ID, vs...))
}

// User2IDEQ applies the EQ predicate on the "user2_id" field.
func User2IDEQ(v int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldUser2ID, v))
}

// User2IDNEQ applies the NEQ predicate on the "user2_id" field.
func User2IDNEQ(v int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldUser2ID, v))
}

// User2IDIn applies the In predicate on the "user2_id" field.
func User2IDIn(vs ...int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldUser2ID, vs...))
}

// User2IDNotIn applies the NotIn predicate on the "user2_id" field.
func User2IDNotIn(vs ...int) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldUser2ID, vs...))
}

// LastMessageAtEQ applies the EQ predicate on the "last_message_at" field.
func LastMessageAtEQ(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastMessageAtNEQ applies the NEQ predicate on the "last_message_at" field.
func LastMessageAtNEQ(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldLastMessageAt, v))
}

// LastMessageAtIn applies the In predicate on the "last_message_at" field.
func LastMessageAtIn(vs ...time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldLastMessageAt, vs...))
}

// LastMessageAtNotIn applies the NotIn predicate on the "last_message_at" field.
func LastMessageAtNotIn(vs ...time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldLastMessageAt, vs...))
}

// LastMessageAtGT applies the GT predicate on the "last_message_at" field.
func LastMessageAtGT(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldLastMessageAt, v))
}

// LastMessageAtGTE applies the GTE predicate on the "last_message_at" field.
func LastMessageAtGTE(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldLastMessageAt, v))
}

// LastMessageAtLT applies the LT predicate on the "last_message_at" field.
func LastMessageAtLT(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldLastMessageAt, v))
}

// LastMessageAtLTE applies the LTE predicate on the "last_message_at" field.
func LastMessageAtLTE(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldLastMessageAt, v))
}

// LastMessageAtIsNil applies the IsNil predicate on the "last_message_at" field.
func LastMessageAtIsNil() predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIsNull(FieldLastMessageAt))
}

// LastMessageAtNotNil applies the NotNil predicate on the "last_message_at" field.
func LastMessageAtNotNil() predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotNull(FieldLastMessageAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DirectMessage {
	return predicate.DirectMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser1 applies the HasEdge predicate on the "user1" edge.
func HasUser1() predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, User1Table, User1Column),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUser1With applies the HasEdge predicate on the "user1" edge with a given conditions (other predicates).
func HasUser1With(preds ...predicate.User) predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := newUser1Step()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser2 applies the HasEdge predicate on the "user2" edge.
func HasUser2() predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, User2Table, User2Column),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUser2With applies the HasEdge predicate on the "user2" edge with a given conditions (other predicates).
func HasUser2With(preds ...predicate.User) predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := newUser2Step()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.DirectMessageContent) predicate.DirectMessage {
	return predicate.DirectMessage(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DirectMessage) predicate.DirectMessage {
	return predicate.DirectMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DirectMessage) predicate.DirectMessage {
	return predicate.DirectMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DirectMessage) predicate.DirectMessage {
	return predicate.DirectMessage(sql.NotPredicates(p))
}
