// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/attachment"
	"github.com/mikestefanello/pagoda/ent/directmessagecontent"
	"github.com/mikestefanello/pagoda/ent/message"
	"github.com/mikestefanello/pagoda/ent/user"
)

// AttachmentCreate is the builder for creating a Attachment entity.
type AttachmentCreate struct {
	config
	mutation *AttachmentMutation
	hooks    []Hook
}

// SetFilename sets the "filename" field.
func (_c *AttachmentCreate) SetFilename(v string) *AttachmentCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetFilepath sets the "filepath" field.
func (_c *AttachmentCreate) SetFilepath(v string) *AttachmentCreate {
	_c.mutation.SetFilepath(v)
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *AttachmentCreate) SetFileSize(v int64) *AttachmentCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *AttachmentCreate) SetMimeType(v string) *AttachmentCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *AttachmentCreate) SetMessageID(v int) *AttachmentCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *AttachmentCreate) SetNillableMessageID(v *int) *AttachmentCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetDmContentID sets the "dm_content_id" field.
func (_c *AttachmentCreate) SetDmContentID(v int) *AttachmentCreate {
	_c.mutation.SetDmContentID(v)
	return _c
}

// SetNillableDmContentID sets the "dm_content_id" field if the given value is not nil.
func (_c *AttachmentCreate) SetNillableDmContentID(v *int) *AttachmentCreate {
	if v != nil {
		_c.SetDmContentID(*v)
	}
	return _c
}

// SetUploadedBy sets the "uploaded_by" field.
func (_c *AttachmentCreate) SetUploadedBy(v int) *AttachmentCreate {
	_c.mutation.SetUploadedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AttachmentCreate) SetCreatedAt(v time.Time) *AttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AttachmentCreate) SetNillableCreatedAt(v *time.Time) *AttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMessage sets the "message" edge to the Message entity.
func (_c *AttachmentCreate) SetMessage(v *Message) *AttachmentCreate {
	return _c.SetMessageID(v.ID)
}

// SetDmContent sets the "dm_content" edge to the DirectMessageContent entity.
func (_c *AttachmentCreate) SetDmContent(v *DirectMessageContent) *AttachmentCreate {
	return _c.SetDmContentID(v.ID)
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_c *AttachmentCreate) SetUploaderID(id int) *AttachmentCreate {
	_c.mutation.SetUploaderID(id)
	return _c
}

// SetUploader sets the "uploader" edge to the User entity.
func (_c *AttachmentCreate) SetUploader(v *User) *AttachmentCreate {
	return _c.SetUploaderID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_c *AttachmentCreate) Mutation() *AttachmentMutation {
	return _c.mutation
}

// Save creates the Attachment in the database.
func (_c *AttachmentCreate) Save(ctx context.Context) (*Attachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AttachmentCreate) SaveX(ctx context.Context) *Attachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AttachmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := attachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AttachmentCreate) check() error {
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "Attachment.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := attachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Attachment.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Filepath(); !ok {
		return &ValidationError{Name: "filepath", err: errors.New(`ent: missing required field "Attachment.filepath"`)}
	}
	if v, ok := _c.mutation.Filepath(); ok {
		if err := attachment.FilepathValidator(v); err != nil {
			return &ValidationError{Name: "filepath", err: fmt.Errorf(`ent: validator failed for field "Attachment.filepath": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "Attachment.file_size"`)}
	}
	if v, ok := _c.mutation.FileSize(); ok {
		if err := attachment.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "Attachment.file_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "Attachment.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := attachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Attachment.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UploadedBy(); !ok {
		return &ValidationError{Name: "uploaded_by", err: errors.New(`ent: missing required field "Attachment.uploaded_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Attachment.created_at"`)}
	}
	if len(_c.mutation.UploaderIDs()) == 0 {
		return &ValidationError{Name: "uploader", err: errors.New(`ent: missing required edge "Attachment.uploader"`)}
	}
	return nil
}

func (_c *AttachmentCreate) sqlSave(ctx context.Context) (*Attachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AttachmentCreate) createSpec() (*Attachment, *sqlgraph.CreateSpec) {
	var (
		_node = &Attachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(attachment.Table, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(attachment.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.Filepath(); ok {
		_spec.SetField(attachment.FieldFilepath, field.TypeString, value)
		_node.Filepath = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(attachment.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(attachment.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(attachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attachment.MessageTable,
			Columns: []string{attachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DmContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attachment.DmContentTable,
			Columns: []string{attachment.DmContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(directmessagecontent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DmContentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attachment.UploaderTable,
			Columns: []string{attachment.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UploadedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttachmentCreateBulk is the builder for creating many Attachment entities in bulk.
type AttachmentCreateBulk struct {
	config
	err      error
	builders []*AttachmentCreate
}

// Save creates the Attachment entities in the database.
func (_c *AttachmentCreateBulk) Save(ctx context.Context) ([]*Attachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Attachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AttachmentCreateBulk) SaveX(ctx context.Context) []*Attachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
