// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/directmessage"
	"github.com/mikestefanello/pagoda/ent/directmessagecontent"
	"github.com/mikestefanello/pagoda/ent/user"
)

// DirectMessageContent is the model entity for the DirectMessageContent schema.
type DirectMessageContent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// DmID holds the value of the "dm_id" field.
	DmID int `json:"dm_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// EditedAt holds the value of the "edited_at" field.
	EditedAt *time.Time `json:"edited_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DirectMessageContentQuery when eager-loading is set.
	Edges                   DirectMessageContentEdges `json:"edges"`
	direct_message_messages *int
	selectValues            sql.SelectValues
}

// DirectMessageContentEdges holds the relations/edges for other nodes in the graph.
type DirectMessageContentEdges struct {
	// Dm holds the value of the dm edge.
	Dm *DirectMessage `json:"dm,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*Attachment `json:"attachments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DmOrErr returns the Dm value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DirectMessageContentEdges) DmOrErr() (*DirectMessage, error) {
	if e.Dm != nil {
		return e.Dm, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: directmessage.Label}
	}
	return nil, &NotLoadedError{edge: "dm"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DirectMessageContentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e DirectMessageContentEdges) AttachmentsOrErr() ([]*Attachment, error) {
	if e.loadedTypes[2] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DirectMessageContent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case directmessagecontent.FieldID, directmessagecontent.FieldDmID, directmessagecontent.FieldUserID:
			values[i] = new(sql.NullInt64)
		case directmessagecontent.FieldContent:
			values[i] = new(sql.NullString)
		case directmessagecontent.FieldCreatedAt, directmessagecontent.FieldEditedAt:
			values[i] = new(sql.NullTime)
		case directmessagecontent.ForeignKeys[0]: // direct_message_messages
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DirectMessageContent fields.
func (_m *DirectMessageContent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case directmessagecontent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case directmessagecontent.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case directmessagecontent.FieldDmID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dm_id", values[i])
			} else if value.Valid {
				_m.DmID = int(value.Int64)
			}
		case directmessagecontent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case directmessagecontent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case directmessagecontent.FieldEditedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field edited_at", values[i])
			} else if value.Valid {
				_m.EditedAt = new(time.Time)
				*_m.EditedAt = value.Time
			}
		case directmessagecontent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field direct_message_messages", value)
			} else if value.Valid {
				_m.direct_message_messages = new(int)
				*_m.direct_message_messages = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DirectMessageContent.
// This includes values selected through modifiers, order, etc.
func (_m *DirectMessageContent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDm queries the "dm" edge of the DirectMessageContent entity.
func (_m *DirectMessageContent) QueryDm() *DirectMessageQuery {
	return NewDirectMessageContentClient(_m.config).QueryDm(_m)
}

// QueryUser queries the "user" edge of the DirectMessageContent entity.
func (_m *DirectMessageContent) QueryUser() *UserQuery {
	return NewDirectMessageContentClient(_m.config).QueryUser(_m)
}

// QueryAttachments queries the "attachments" edge of the DirectMessageContent entity.
func (_m *DirectMessageContent) QueryAttachments() *AttachmentQuery {
	return NewDirectMessageContentClient(_m.config).QueryAttachments(_m)
}

// Update returns a builder for updating this DirectMessageContent.
// Note that you need to call DirectMessageContent.Unwrap() before calling this method if this DirectMessageContent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DirectMessageContent) Update() *DirectMessageContentUpdateOne {
	return NewDirectMessageContentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DirectMessageContent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DirectMessageContent) Unwrap() *DirectMessageContent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DirectMessageContent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DirectMessageContent) String() string {
	var builder strings.Builder
	builder.WriteString("DirectMessageContent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("dm_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DmID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EditedAt; v != nil {
		builder.WriteString("edited_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DirectMessageContents is a parsable slice of DirectMessageContent.
type DirectMessageContents []*DirectMessageContent
