// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/attachment"
	"github.com/mikestefanello/pagoda/ent/directmessage"
	"github.com/mikestefanello/pagoda/ent/directmessagecontent"
	"github.com/mikestefanello/pagoda/ent/user"
)

// DirectMessageContentCreate is the builder for creating a DirectMessageContent entity.
type DirectMessageContentCreate struct {
	config
	mutation *DirectMessageContentMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (_c *DirectMessageContentCreate) SetContent(v string) *DirectMessageContentCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetDmID sets the "dm_id" field.
func (_c *DirectMessageContentCreate) SetDmID(v int) *DirectMessageContentCreate {
	_c.mutation.SetDmID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DirectMessageContentCreate) SetUserID(v int) *DirectMessageContentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DirectMessageContentCreate) SetCreatedAt(v time.Time) *DirectMessageContentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DirectMessageContentCreate) SetNillableCreatedAt(v *time.Time) *DirectMessageContentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEditedAt sets the "edited_at" field.
func (_c *DirectMessageContentCreate) SetEditedAt(v time.Time) *DirectMessageContentCreate {
	_c.mutation.SetEditedAt(v)
	return _c
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_c *DirectMessageContentCreate) SetNillableEditedAt(v *time.Time) *DirectMessageContentCreate {
	if v != nil {
		_c.SetEditedAt(*v)
	}
	return _c
}

// SetDm sets the "dm" edge to the DirectMessage entity.
func (_c *DirectMessageContentCreate) SetDm(v *DirectMessage) *DirectMessageContentCreate {
	return _c.SetDmID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *DirectMessageContentCreate) SetUser(v *User) *DirectMessageContentCreate {
	return _c.SetUserID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_c *DirectMessageContentCreate) AddAttachmentIDs(ids ...int) *DirectMessageContentCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_c *DirectMessageContentCreate) AddAttachments(v ...*Attachment) *DirectMessageContentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// Mutation returns the DirectMessageContentMutation object of the builder.
func (_c *DirectMessageContentCreate) Mutation() *DirectMessageContentMutation {
	return _c.mutation
}

// Save creates the DirectMessageContent in the database.
func (_c *DirectMessageContentCreate) Save(ctx context.Context) (*DirectMessageContent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DirectMessageContentCreate) SaveX(ctx context.Context) *DirectMessageContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirectMessageContentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirectMessageContentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DirectMessageContentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := directmessagecontent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DirectMessageContentCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "DirectMessageContent.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := directmessagecontent.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "DirectMessageContent.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DmID(); !ok {
		return &ValidationError{Name: "dm_id", err: errors.New(`ent: missing required field "DirectMessageContent.dm_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DirectMessageContent.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DirectMessageContent.created_at"`)}
	}
	if len(_c.mutation.DmIDs()) == 0 {
		return &ValidationError{Name: "dm", err: errors.New(`ent: missing required edge "DirectMessageContent.dm"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DirectMessageContent.user"`)}
	}
	return nil
}

func (_c *DirectMessageContentCreate) sqlSave(ctx context.Context) (*DirectMessageContent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DirectMessageContentCreate) createSpec() (*DirectMessageContent, *sqlgraph.CreateSpec) {
	var (
		_node = &DirectMessageContent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(directmessagecontent.Table, sqlgraph.NewFieldSpec(directmessagecontent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(directmessagecontent.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(directmessagecontent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.EditedAt(); ok {
		_spec.SetField(directmessagecontent.FieldEditedAt, field.TypeTime, value)
		_node.EditedAt = &value
	}
	if nodes := _c.mutation.DmIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.DmTable,
			Columns: []string{directmessagecontent.DmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DmID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.UserTable,
			Columns: []string{directmessagecontent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directmessagecontent.AttachmentsTable,
			Columns: []string{directmessagecontent.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DirectMessageContentCreateBulk is the builder for creating many DirectMessageContent entities in bulk.
type DirectMessageContentCreateBulk struct {
	config
	err      error
	builders []*DirectMessageContentCreate
}

// Save creates the DirectMessageContent entities in the database.
func (_c *DirectMessageContentCreateBulk) Save(ctx context.Context) ([]*DirectMessageContent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DirectMessageContent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DirectMessageContentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DirectMessageContentCreateBulk) SaveX(ctx context.Context) []*DirectMessageContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DirectMessageContentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DirectMessageContentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
