// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/attachment"
	"github.com/mikestefanello/pagoda/ent/directmessage"
	"github.com/mikestefanello/pagoda/ent/directmessagecontent"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
)

// DirectMessageContentUpdate is the builder for updating DirectMessageContent entities.
type DirectMessageContentUpdate struct {
	config
	hooks    []Hook
	mutation *DirectMessageContentMutation
}

// Where appends a list predicates to the DirectMessageContentUpdate builder.
func (_u *DirectMessageContentUpdate) Where(ps ...predicate.DirectMessageContent) *DirectMessageContentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *DirectMessageContentUpdate) SetContent(v string) *DirectMessageContentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DirectMessageContentUpdate) SetNillableContent(v *string) *DirectMessageContentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetDmID sets the "dm_id" field.
func (_u *DirectMessageContentUpdate) SetDmID(v int) *DirectMessageContentUpdate {
	_u.mutation.SetDmID(v)
	return _u
}

// SetNillableDmID sets the "dm_id" field if the given value is not nil.
func (_u *DirectMessageContentUpdate) SetNillableDmID(v *int) *DirectMessageContentUpdate {
	if v != nil {
		_u.SetDmID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DirectMessageContentUpdate) SetUserID(v int) *DirectMessageContentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DirectMessageContentUpdate) SetNillableUserID(v *int) *DirectMessageContentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *DirectMessageContentUpdate) SetEditedAt(v time.Time) *DirectMessageContentUpdate {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *DirectMessageContentUpdate) SetNillableEditedAt(v *time.Time) *DirectMessageContentUpdate {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *DirectMessageContentUpdate) ClearEditedAt() *DirectMessageContentUpdate {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetDm sets the "dm" edge to the DirectMessage entity.
func (_u *DirectMessageContentUpdate) SetDm(v *DirectMessage) *DirectMessageContentUpdate {
	return _u.SetDmID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DirectMessageContentUpdate) SetUser(v *User) *DirectMessageContentUpdate {
	return _u.SetUserID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *DirectMessageContentUpdate) AddAttachmentIDs(ids ...int) *DirectMessageContentUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *DirectMessageContentUpdate) AddAttachments(v ...*Attachment) *DirectMessageContentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the DirectMessageContentMutation object of the builder.
func (_u *DirectMessageContentUpdate) Mutation() *DirectMessageContentMutation {
	return _u.mutation
}

// ClearDm clears the "dm" edge to the DirectMessage entity.
func (_u *DirectMessageContentUpdate) ClearDm() *DirectMessageContentUpdate {
	_u.mutation.ClearDm()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DirectMessageContentUpdate) ClearUser() *DirectMessageContentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *DirectMessageContentUpdate) ClearAttachments() *DirectMessageContentUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *DirectMessageContentUpdate) RemoveAttachmentIDs(ids ...int) *DirectMessageContentUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *DirectMessageContentUpdate) RemoveAttachments(v ...*Attachment) *DirectMessageContentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DirectMessageContentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DirectMessageContentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DirectMessageContentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DirectMessageContentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DirectMessageContentUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := directmessagecontent.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "DirectMessageContent.content": %w`, err)}
		}
	}
	if _u.mutation.DmCleared() && len(_u.mutation.DmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessageContent.dm"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessageContent.user"`)
	}
	return nil
}

func (_u *DirectMessageContentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(directmessagecontent.Table, directmessagecontent.Columns, sqlgraph.NewFieldSpec(directmessagecontent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(directmessagecontent.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(directmessagecontent.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(directmessagecontent.FieldEditedAt, field.TypeTime)
	}
	if _u.mutation.DmCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.DmTable,
			Columns: []string{directmessagecontent.DmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DmIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.DmTable,
			Columns: []string{directmessagecontent.DmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.UserTable,
			Columns: []string{directmessagecontent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.UserTable,
			Columns: []string{directmessagecontent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directmessagecontent.AttachmentsTable,
			Columns: []string{directmessagecontent.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directmessagecontent.AttachmentsTable,
			Columns: []string{directmessagecontent.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directmessagecontent.AttachmentsTable,
			Columns: []string{directmessagecontent.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directmessagecontent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DirectMessageContentUpdateOne is the builder for updating a single DirectMessageContent entity.
type DirectMessageContentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirectMessageContentMutation
}

// SetContent sets the "content" field.
func (_u *DirectMessageContentUpdateOne) SetContent(v string) *DirectMessageContentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DirectMessageContentUpdateOne) SetNillableContent(v *string) *DirectMessageContentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetDmID sets the "dm_id" field.
func (_u *DirectMessageContentUpdateOne) SetDmID(v int) *DirectMessageContentUpdateOne {
	_u.mutation.SetDmID(v)
	return _u
}

// SetNillableDmID sets the "dm_id" field if the given value is not nil.
func (_u *DirectMessageContentUpdateOne) SetNillableDmID(v *int) *DirectMessageContentUpdateOne {
	if v != nil {
		_u.SetDmID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DirectMessageContentUpdateOne) SetUserID(v int) *DirectMessageContentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DirectMessageContentUpdateOne) SetNillableUserID(v *int) *DirectMessageContentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *DirectMessageContentUpdateOne) SetEditedAt(v time.Time) *DirectMessageContentUpdateOne {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *DirectMessageContentUpdateOne) SetNillableEditedAt(v *time.Time) *DirectMessageContentUpdateOne {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *DirectMessageContentUpdateOne) ClearEditedAt() *DirectMessageContentUpdateOne {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetDm sets the "dm" edge to the DirectMessage entity.
func (_u *DirectMessageContentUpdateOne) SetDm(v *DirectMessage) *DirectMessageContentUpdateOne {
	return _u.SetDmID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DirectMessageContentUpdateOne) SetUser(v *User) *DirectMessageContentUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *DirectMessageContentUpdateOne) AddAttachmentIDs(ids ...int) *DirectMessageContentUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *DirectMessageContentUpdateOne) AddAttachments(v ...*Attachment) *DirectMessageContentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the DirectMessageContentMutation object of the builder.
func (_u *DirectMessageContentUpdateOne) Mutation() *DirectMessageContentMutation {
	return _u.mutation
}

// ClearDm clears the "dm" edge to the DirectMessage entity.
func (_u *DirectMessageContentUpdateOne) ClearDm() *DirectMessageContentUpdateOne {
	_u.mutation.ClearDm()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DirectMessageContentUpdateOne) ClearUser() *DirectMessageContentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *DirectMessageContentUpdateOne) ClearAttachments() *DirectMessageContentUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *DirectMessageContentUpdateOne) RemoveAttachmentIDs(ids ...int) *DirectMessageContentUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *DirectMessageContentUpdateOne) RemoveAttachments(v ...*Attachment) *DirectMessageContentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the DirectMessageContentUpdate builder.
func (_u *DirectMessageContentUpdateOne) Where(ps ...predicate.DirectMessageContent) *DirectMessageContentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DirectMessageContentUpdateOne) Select(field string, fields ...string) *DirectMessageContentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DirectMessageContent entity.
func (_u *DirectMessageContentUpdateOne) Save(ctx context.Context) (*DirectMessageContent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DirectMessageContentUpdateOne) SaveX(ctx context.Context) *DirectMessageContent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DirectMessageContentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DirectMessageContentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DirectMessageContentUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := directmessagecontent.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "DirectMessageContent.content": %w`, err)}
		}
	}
	if _u.mutation.DmCleared() && len(_u.mutation.DmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessageContent.dm"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DirectMessageContent.user"`)
	}
	return nil
}

func (_u *DirectMessageContentUpdateOne) sqlSave(ctx context.Context) (_node *DirectMessageContent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(directmessagecontent.Table, directmessagecontent.Columns, sqlgraph.NewFieldSpec(directmessagecontent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DirectMessageContent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, directmessagecontent.FieldID)
		for _, f := range fields {
			if !directmessagecontent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != directmessagecontent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(directmessagecontent.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(directmessagecontent.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(directmessagecontent.FieldEditedAt, field.TypeTime)
	}
	if _u.mutation.DmCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.DmTable,
			Columns: []string{directmessagecontent.DmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DmIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.DmTable,
			Columns: []string{directmessagecontent.DmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(directmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.UserTable,
			Columns: []string{directmessagecontent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   directmessagecontent.UserTable,
			Columns: []string{directmessagecontent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directmessagecontent.AttachmentsTable,
			Columns: []string{directmessagecontent.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directmessagecontent.AttachmentsTable,
			Columns: []string{directmessagecontent.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directmessagecontent.AttachmentsTable,
			Columns: []string{directmessagecontent.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DirectMessageContent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directmessagecontent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
