// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/attachment"
	"github.com/mikestefanello/pagoda/ent/directmessage"
	"github.com/mikestefanello/pagoda/ent/directmessagecontent"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
)

// DirectMessageContentQuery is the builder for querying DirectMessageContent entities.
type DirectMessageContentQuery struct {
	config
	ctx             *QueryContext
	order           []directmessagecontent.OrderOption
	inters          []Interceptor
	predicates      []predicate.DirectMessageContent
	withDm          *DirectMessageQuery
	withUser        *UserQuery
	withAttachments *AttachmentQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DirectMessageContentQuery builder.
func (_q *DirectMessageContentQuery) Where(ps ...predicate.DirectMessageContent) *DirectMessageContentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DirectMessageContentQuery) Limit(limit int) *DirectMessageContentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DirectMessageContentQuery) Offset(offset int) *DirectMessageContentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DirectMessageContentQuery) Unique(unique bool) *DirectMessageContentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DirectMessageContentQuery) Order(o ...directmessagecontent.OrderOption) *DirectMessageContentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDm chains the current query on the "dm" edge.
func (_q *DirectMessageContentQuery) QueryDm() *DirectMessageQuery {
	query := (&DirectMessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(directmessagecontent.Table, directmessagecontent.FieldID, selector),
			sqlgraph.To(directmessage.Table, directmessage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, directmessagecontent.DmTable, directmessagecontent.DmColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *DirectMessageContentQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(directmessagecontent.Table, directmessagecontent.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, directmessagecontent.UserTable, directmessagecontent.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttachments chains the current query on the "attachments" edge.
func (_q *DirectMessageContentQuery) QueryAttachments() *AttachmentQuery {
	query := (&AttachmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(directmessagecontent.Table, directmessagecontent.FieldID, selector),
			sqlgraph.To(attachment.Table, attachment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, directmessagecontent.AttachmentsTable, directmessagecontent.AttachmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DirectMessageContent entity from the query.
// Returns a *NotFoundError when no DirectMessageContent was found.
func (_q *DirectMessageContentQuery) First(ctx context.Context) (*DirectMessageContent, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{directmessagecontent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DirectMessageContentQuery) FirstX(ctx context.Context) *DirectMessageContent {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DirectMessageContent ID from the query.
// Returns a *NotFoundError when no DirectMessageContent ID was found.
func (_q *DirectMessageContentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{directmessagecontent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DirectMessageContentQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DirectMessageContent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DirectMessageContent entity is found.
// Returns a *NotFoundError when no DirectMessageContent entities are found.
func (_q *DirectMessageContentQuery) Only(ctx context.Context) (*DirectMessageContent, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{directmessagecontent.Label}
	default:
		return nil, &NotSingularError{directmessagecontent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DirectMessageContentQuery) OnlyX(ctx context.Context) *DirectMessageContent {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DirectMessageContent ID in the query.
// Returns a *NotSingularError when more than one DirectMessageContent ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DirectMessageContentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{directmessagecontent.Label}
	default:
		err = &NotSingularError{directmessagecontent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DirectMessageContentQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DirectMessageContents.
func (_q *DirectMessageContentQuery) All(ctx context.Context) ([]*DirectMessageContent, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DirectMessageContent, *DirectMessageContentQuery]()
	return withInterceptors[[]*DirectMessageContent](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DirectMessageContentQuery) AllX(ctx context.Context) []*DirectMessageContent {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DirectMessageContent IDs.
func (_q *DirectMessageContentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(directmessagecontent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DirectMessageContentQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DirectMessageContentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DirectMessageContentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DirectMessageContentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DirectMessageContentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DirectMessageContentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DirectMessageContentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DirectMessageContentQuery) Clone() *DirectMessageContentQuery {
	if _q == nil {
		return nil
	}
	return &DirectMessageContentQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]directmessagecontent.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.DirectMessageContent{}, _q.predicates...),
		withDm:          _q.withDm.Clone(),
		withUser:        _q.withUser.Clone(),
		withAttachments: _q.withAttachments.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDm tells the query-builder to eager-load the nodes that are connected to
// the "dm" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DirectMessageContentQuery) WithDm(opts ...func(*DirectMessageQuery)) *DirectMessageContentQuery {
	query := (&DirectMessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDm = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DirectMessageContentQuery) WithUser(opts ...func(*UserQuery)) *DirectMessageContentQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithAttachments tells the query-builder to eager-load the nodes that are connected to
// the "attachments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DirectMessageContentQuery) WithAttachments(opts ...func(*AttachmentQuery)) *DirectMessageContentQuery {
	query := (&AttachmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttachments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DirectMessageContent.Query().
//		GroupBy(directmessagecontent.FieldContent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DirectMessageContentQuery) GroupBy(field string, fields ...string) *DirectMessageContentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DirectMessageContentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = directmessagecontent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//	}
//
//	client.DirectMessageContent.Query().
//		Select(directmessagecontent.FieldContent).
//		Scan(ctx, &v)
func (_q *DirectMessageContentQuery) Select(fields ...string) *DirectMessageContentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DirectMessageContentSelect{DirectMessageContentQuery: _q}
	sbuild.label = directmessagecontent.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DirectMessageContentSelect configured with the given aggregations.
func (_q *DirectMessageContentQuery) Aggregate(fns ...AggregateFunc) *DirectMessageContentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DirectMessageContentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !directmessagecontent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DirectMessageContentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DirectMessageContent, error) {
	var (
		nodes       = []*DirectMessageContent{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withDm != nil,
			_q.withUser != nil,
			_q.withAttachments != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, directmessagecontent.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DirectMessageContent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DirectMessageContent{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDm; query != nil {
		if err := _q.loadDm(ctx, query, nodes, nil,
			func(n *DirectMessageContent, e *DirectMessage) { n.Edges.Dm = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *DirectMessageContent, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttachments; query != nil {
		if err := _q.loadAttachments(ctx, query, nodes,
			func(n *DirectMessageContent) { n.Edges.Attachments = []*Attachment{} },
			func(n *DirectMessageContent, e *Attachment) { n.Edges.Attachments = append(n.Edges.Attachments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DirectMessageContentQuery) loadDm(ctx context.Context, query *DirectMessageQuery, nodes []*DirectMessageContent, init func(*DirectMessageContent), assign func(*DirectMessageContent, *DirectMessage)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DirectMessageContent)
	for i := range nodes {
		fk := nodes[i].DmID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(directmessage.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "dm_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DirectMessageContentQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*DirectMessageContent, init func(*DirectMessageContent), assign func(*DirectMessageContent, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DirectMessageContent)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DirectMessageContentQuery) loadAttachments(ctx context.Context, query *AttachmentQuery, nodes []*DirectMessageContent, init func(*DirectMessageContent), assign func(*DirectMessageContent, *Attachment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DirectMessageContent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Attachment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(directmessagecontent.AttachmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.direct_message_content_attachments
		if fk == nil {
			return fmt.Errorf(`foreign-key "direct_message_content_attachments" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "direct_message_content_attachments" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DirectMessageContentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DirectMessageContentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(directmessagecontent.Table, directmessagecontent.Columns, sqlgraph.NewFieldSpec(directmessagecontent.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, directmessagecontent.FieldID)
		for i := range fields {
			if fields[i] != directmessagecontent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDm != nil {
			_spec.Node.AddColumnOnce(directmessagecontent.FieldDmID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(directmessagecontent.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DirectMessageContentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(directmessagecontent.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = directmessagecontent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DirectMessageContentGroupBy is the group-by builder for DirectMessageContent entities.
type DirectMessageContentGroupBy struct {
	selector
	build *DirectMessageContentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DirectMessageContentGroupBy) Aggregate(fns ...AggregateFunc) *DirectMessageContentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DirectMessageContentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectMessageContentQuery, *DirectMessageContentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DirectMessageContentGroupBy) sqlScan(ctx context.Context, root *DirectMessageContentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DirectMessageContentSelect is the builder for selecting fields of DirectMessageContent entities.
type DirectMessageContentSelect struct {
	*DirectMessageContentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DirectMessageContentSelect) Aggregate(fns ...AggregateFunc) *DirectMessageContentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DirectMessageContentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirectMessageContentQuery, *DirectMessageContentSelect](ctx, _s.DirectMessageContentQuery, _s, _s.inters, v)
}

func (_s *DirectMessageContentSelect) sqlScan(ctx context.Context, root *DirectMessageContentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
