// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/attachment"
	"github.com/mikestefanello/pagoda/ent/channel"
	"github.com/mikestefanello/pagoda/ent/message"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/reaction"
	"github.com/mikestefanello/pagoda/ent/user"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *MessageUpdate) SetMessageType(v message.MessageType) *MessageUpdate {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableMessageType(v *message.MessageType) *MessageUpdate {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *MessageUpdate) SetChannelID(v int) *MessageUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableChannelID(v *int) *MessageUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MessageUpdate) SetUserID(v int) *MessageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableUserID(v *int) *MessageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *MessageUpdate) SetThreadID(v int) *MessageUpdate {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableThreadID(v *int) *MessageUpdate {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// ClearThreadID clears the value of the "thread_id" field.
func (_u *MessageUpdate) ClearThreadID() *MessageUpdate {
	_u.mutation.ClearThreadID()
	return _u
}

// SetReplyCount sets the "reply_count" field.
func (_u *MessageUpdate) SetReplyCount(v int) *MessageUpdate {
	_u.mutation.ResetReplyCount()
	_u.mutation.SetReplyCount(v)
	return _u
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableReplyCount(v *int) *MessageUpdate {
	if v != nil {
		_u.SetReplyCount(*v)
	}
	return _u
}

// AddReplyCount adds value to the "reply_count" field.
func (_u *MessageUpdate) AddReplyCount(v int) *MessageUpdate {
	_u.mutation.AddReplyCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageUpdate) SetUpdatedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *MessageUpdate) SetEditedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableEditedAt(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *MessageUpdate) ClearEditedAt() *MessageUpdate {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *MessageUpdate) SetChannel(v *Channel) *MessageUpdate {
	return _u.SetChannelID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *MessageUpdate) SetUser(v *User) *MessageUpdate {
	return _u.SetUserID(v.ID)
}

// SetThread sets the "thread" edge to the Message entity.
func (_u *MessageUpdate) SetThread(v *Message) *MessageUpdate {
	return _u.SetThreadID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the Message entity by IDs.
func (_u *MessageUpdate) AddReplyIDs(ids ...int) *MessageUpdate {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the Message entity.
func (_u *MessageUpdate) AddReplies(v ...*Message) *MessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// AddReactionIDs adds the "reactions" edge to the Reaction entity by IDs.
func (_u *MessageUpdate) AddReactionIDs(ids ...int) *MessageUpdate {
	_u.mutation.AddReactionIDs(ids...)
	return _u
}

// AddReactions adds the "reactions" edges to the Reaction entity.
func (_u *MessageUpdate) AddReactions(v ...*Reaction) *MessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReactionIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *MessageUpdate) AddAttachmentIDs(ids ...int) *MessageUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *MessageUpdate) AddAttachments(v ...*Attachment) *MessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *MessageUpdate) ClearChannel() *MessageUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MessageUpdate) ClearUser() *MessageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearThread clears the "thread" edge to the Message entity.
func (_u *MessageUpdate) ClearThread() *MessageUpdate {
	_u.mutation.ClearThread()
	return _u
}

// ClearReplies clears all "replies" edges to the Message entity.
func (_u *MessageUpdate) ClearReplies() *MessageUpdate {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to Message entities by IDs.
func (_u *MessageUpdate) RemoveReplyIDs(ids ...int) *MessageUpdate {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to Message entities.
func (_u *MessageUpdate) RemoveReplies(v ...*Message) *MessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// ClearReactions clears all "reactions" edges to the Reaction entity.
func (_u *MessageUpdate) ClearReactions() *MessageUpdate {
	_u.mutation.ClearReactions()
	return _u
}

// RemoveReactionIDs removes the "reactions" edge to Reaction entities by IDs.
func (_u *MessageUpdate) RemoveReactionIDs(ids ...int) *MessageUpdate {
	_u.mutation.RemoveReactionIDs(ids...)
	return _u
}

// RemoveReactions removes "reactions" edges to Reaction entities.
func (_u *MessageUpdate) RemoveReactions(v ...*Reaction) *MessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReactionIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *MessageUpdate) ClearAttachments() *MessageUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *MessageUpdate) RemoveAttachmentIDs(ids ...int) *MessageUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *MessageUpdate) RemoveAttachments(v ...*Attachment) *MessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := message.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Message.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageType(); ok {
		if err := message.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "Message.message_type": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.user"`)
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(message.FieldMessageType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReplyCount(); ok {
		_spec.SetField(message.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyCount(); ok {
		_spec.AddField(message.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(message.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(message.FieldEditedAt, field.TypeTime)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ThreadTable,
			Columns: []string{message.ThreadColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ThreadTable,
			Columns: []string{message.ThreadColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReactionsIDs(); len(nodes) > 0 && !_u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *MessageUpdateOne) SetMessageType(v message.MessageType) *MessageUpdateOne {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableMessageType(v *message.MessageType) *MessageUpdateOne {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *MessageUpdateOne) SetChannelID(v int) *MessageUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableChannelID(v *int) *MessageUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MessageUpdateOne) SetUserID(v int) *MessageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableUserID(v *int) *MessageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *MessageUpdateOne) SetThreadID(v int) *MessageUpdateOne {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableThreadID(v *int) *MessageUpdateOne {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// ClearThreadID clears the value of the "thread_id" field.
func (_u *MessageUpdateOne) ClearThreadID() *MessageUpdateOne {
	_u.mutation.ClearThreadID()
	return _u
}

// SetReplyCount sets the "reply_count" field.
func (_u *MessageUpdateOne) SetReplyCount(v int) *MessageUpdateOne {
	_u.mutation.ResetReplyCount()
	_u.mutation.SetReplyCount(v)
	return _u
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableReplyCount(v *int) *MessageUpdateOne {
	if v != nil {
		_u.SetReplyCount(*v)
	}
	return _u
}

// AddReplyCount adds value to the "reply_count" field.
func (_u *MessageUpdateOne) AddReplyCount(v int) *MessageUpdateOne {
	_u.mutation.AddReplyCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageUpdateOne) SetUpdatedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *MessageUpdateOne) SetEditedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableEditedAt(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *MessageUpdateOne) ClearEditedAt() *MessageUpdateOne {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *MessageUpdateOne) SetChannel(v *Channel) *MessageUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *MessageUpdateOne) SetUser(v *User) *MessageUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetThread sets the "thread" edge to the Message entity.
func (_u *MessageUpdateOne) SetThread(v *Message) *MessageUpdateOne {
	return _u.SetThreadID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the Message entity by IDs.
func (_u *MessageUpdateOne) AddReplyIDs(ids ...int) *MessageUpdateOne {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the Message entity.
func (_u *MessageUpdateOne) AddReplies(v ...*Message) *MessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// AddReactionIDs adds the "reactions" edge to the Reaction entity by IDs.
func (_u *MessageUpdateOne) AddReactionIDs(ids ...int) *MessageUpdateOne {
	_u.mutation.AddReactionIDs(ids...)
	return _u
}

// AddReactions adds the "reactions" edges to the Reaction entity.
func (_u *MessageUpdateOne) AddReactions(v ...*Reaction) *MessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReactionIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *MessageUpdateOne) AddAttachmentIDs(ids ...int) *MessageUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *MessageUpdateOne) AddAttachments(v ...*Attachment) *MessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *MessageUpdateOne) ClearChannel() *MessageUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MessageUpdateOne) ClearUser() *MessageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearThread clears the "thread" edge to the Message entity.
func (_u *MessageUpdateOne) ClearThread() *MessageUpdateOne {
	_u.mutation.ClearThread()
	return _u
}

// ClearReplies clears all "replies" edges to the Message entity.
func (_u *MessageUpdateOne) ClearReplies() *MessageUpdateOne {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to Message entities by IDs.
func (_u *MessageUpdateOne) RemoveReplyIDs(ids ...int) *MessageUpdateOne {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to Message entities.
func (_u *MessageUpdateOne) RemoveReplies(v ...*Message) *MessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// ClearReactions clears all "reactions" edges to the Reaction entity.
func (_u *MessageUpdateOne) ClearReactions() *MessageUpdateOne {
	_u.mutation.ClearReactions()
	return _u
}

// RemoveReactionIDs removes the "reactions" edge to Reaction entities by IDs.
func (_u *MessageUpdateOne) RemoveReactionIDs(ids ...int) *MessageUpdateOne {
	_u.mutation.RemoveReactionIDs(ids...)
	return _u
}

// RemoveReactions removes "reactions" edges to Reaction entities.
func (_u *MessageUpdateOne) RemoveReactions(v ...*Reaction) *MessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReactionIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *MessageUpdateOne) ClearAttachments() *MessageUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *MessageUpdateOne) RemoveAttachmentIDs(ids ...int) *MessageUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *MessageUpdateOne) RemoveAttachments(v ...*Attachment) *MessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := message.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Message.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageType(); ok {
		if err := message.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "Message.message_type": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.user"`)
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(message.FieldMessageType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReplyCount(); ok {
		_spec.SetField(message.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyCount(); ok {
		_spec.AddField(message.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(message.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(message.FieldEditedAt, field.TypeTime)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ChannelTable,
			Columns: []string{message.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ThreadTable,
			Columns: []string{message.ThreadColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ThreadTable,
			Columns: []string{message.ThreadColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.RepliesTable,
			Columns: []string{message.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReactionsIDs(); len(nodes) > 0 && !_u.mutation.ReactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ReactionsTable,
			Columns: []string{message.ReactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
