// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/message"
	"github.com/mikestefanello/pagoda/ent/reaction"
	"github.com/mikestefanello/pagoda/ent/user"
)

// ReactionCreate is the builder for creating a Reaction entity.
type ReactionCreate struct {
	config
	mutation *ReactionMutation
	hooks    []Hook
}

// SetEmoji sets the "emoji" field.
func (_c *ReactionCreate) SetEmoji(v string) *ReactionCreate {
	_c.mutation.SetEmoji(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *ReactionCreate) SetMessageID(v int) *ReactionCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ReactionCreate) SetUserID(v int) *ReactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReactionCreate) SetCreatedAt(v time.Time) *ReactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReactionCreate) SetNillableCreatedAt(v *time.Time) *ReactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMessage sets the "message" edge to the Message entity.
func (_c *ReactionCreate) SetMessage(v *Message) *ReactionCreate {
	return _c.SetMessageID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ReactionCreate) SetUser(v *User) *ReactionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ReactionMutation object of the builder.
func (_c *ReactionCreate) Mutation() *ReactionMutation {
	return _c.mutation
}

// Save creates the Reaction in the database.
func (_c *ReactionCreate) Save(ctx context.Context) (*Reaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReactionCreate) SaveX(ctx context.Context) *Reaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReactionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReactionCreate) check() error {
	if _, ok := _c.mutation.Emoji(); !ok {
		return &ValidationError{Name: "emoji", err: errors.New(`ent: missing required field "Reaction.emoji"`)}
	}
	if v, ok := _c.mutation.Emoji(); ok {
		if err := reaction.EmojiValidator(v); err != nil {
			return &ValidationError{Name: "emoji", err: fmt.Errorf(`ent: validator failed for field "Reaction.emoji": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "Reaction.message_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Reaction.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Reaction.created_at"`)}
	}
	if len(_c.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "Reaction.message"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Reaction.user"`)}
	}
	return nil
}

func (_c *ReactionCreate) sqlSave(ctx context.Context) (*Reaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReactionCreate) createSpec() (*Reaction, *sqlgraph.CreateSpec) {
	var (
		_node = &Reaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reaction.Table, sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Emoji(); ok {
		_spec.SetField(reaction.FieldEmoji, field.TypeString, value)
		_node.Emoji = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   reaction.MessageTable,
			Columns: []string{reaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   reaction.UserTable,
			Columns: []string{reaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReactionCreateBulk is the builder for creating many Reaction entities in bulk.
type ReactionCreateBulk struct {
	config
	err      error
	builders []*ReactionCreate
}

// Save creates the Reaction entities in the database.
func (_c *ReactionCreateBulk) Save(ctx context.Context) ([]*Reaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Reaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReactionCreateBulk) SaveX(ctx context.Context) []*Reaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
