// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
	"github.com/mikestefanello/pagoda/ent/userprofile"
)

// UserProfileUpdate is the builder for updating UserProfile entities.
type UserProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserProfileMutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdate) Where(ps ...predicate.UserProfile) *UserProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserProfileUpdate) SetUserID(v int) *UserProfileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableUserID(v *int) *UserProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserProfileUpdate) SetAvatarURL(v string) *UserProfileUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableAvatarURL(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserProfileUpdate) ClearAvatarURL() *UserProfileUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserProfileUpdate) SetStatus(v userprofile.Status) *UserProfileUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableStatus(v *userprofile.Status) *UserProfileUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusMessage sets the "status_message" field.
func (_u *UserProfileUpdate) SetStatusMessage(v string) *UserProfileUpdate {
	_u.mutation.SetStatusMessage(v)
	return _u
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableStatusMessage(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetStatusMessage(*v)
	}
	return _u
}

// ClearStatusMessage clears the value of the "status_message" field.
func (_u *UserProfileUpdate) ClearStatusMessage() *UserProfileUpdate {
	_u.mutation.ClearStatusMessage()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *UserProfileUpdate) SetTimezone(v string) *UserProfileUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableTimezone(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *UserProfileUpdate) ClearTimezone() *UserProfileUpdate {
	_u.mutation.ClearTimezone()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserProfileUpdate) SetUser(v *User) *UserProfileUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdate) Mutation() *UserProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserProfileUpdate) ClearUser() *UserProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserProfileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdate) check() error {
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := userprofile.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.avatar_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserProfile.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusMessage(); ok {
		if err := userprofile.StatusMessageValidator(v); err != nil {
			return &ValidationError{Name: "status_message", err: fmt.Errorf(`ent: validator failed for field "UserProfile.status_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := userprofile.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "UserProfile.timezone": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserProfile.user"`)
	}
	return nil
}

func (_u *UserProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(userprofile.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(userprofile.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userprofile.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusMessage(); ok {
		_spec.SetField(userprofile.FieldStatusMessage, field.TypeString, value)
	}
	if _u.mutation.StatusMessageCleared() {
		_spec.ClearField(userprofile.FieldStatusMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(userprofile.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(userprofile.FieldTimezone, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserProfileUpdateOne is the builder for updating a single UserProfile entity.
type UserProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserProfileMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserProfileUpdateOne) SetUserID(v int) *UserProfileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableUserID(v *int) *UserProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserProfileUpdateOne) SetAvatarURL(v string) *UserProfileUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableAvatarURL(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserProfileUpdateOne) ClearAvatarURL() *UserProfileUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserProfileUpdateOne) SetStatus(v userprofile.Status) *UserProfileUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableStatus(v *userprofile.Status) *UserProfileUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusMessage sets the "status_message" field.
func (_u *UserProfileUpdateOne) SetStatusMessage(v string) *UserProfileUpdateOne {
	_u.mutation.SetStatusMessage(v)
	return _u
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableStatusMessage(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetStatusMessage(*v)
	}
	return _u
}

// ClearStatusMessage clears the value of the "status_message" field.
func (_u *UserProfileUpdateOne) ClearStatusMessage() *UserProfileUpdateOne {
	_u.mutation.ClearStatusMessage()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *UserProfileUpdateOne) SetTimezone(v string) *UserProfileUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableTimezone(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *UserProfileUpdateOne) ClearTimezone() *UserProfileUpdateOne {
	_u.mutation.ClearTimezone()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserProfileUpdateOne) SetUser(v *User) *UserProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdateOne) Mutation() *UserProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserProfileUpdateOne) ClearUser() *UserProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdateOne) Where(ps ...predicate.UserProfile) *UserProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserProfileUpdateOne) Select(field string, fields ...string) *UserProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserProfile entity.
func (_u *UserProfileUpdateOne) Save(ctx context.Context) (*UserProfile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdateOne) SaveX(ctx context.Context) *UserProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdateOne) check() error {
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := userprofile.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.avatar_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserProfile.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusMessage(); ok {
		if err := userprofile.StatusMessageValidator(v); err != nil {
			return &ValidationError{Name: "status_message", err: fmt.Errorf(`ent: validator failed for field "UserProfile.status_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := userprofile.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "UserProfile.timezone": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserProfile.user"`)
	}
	return nil
}

func (_u *UserProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userprofile.FieldID)
		for _, f := range fields {
			if !userprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(userprofile.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(userprofile.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userprofile.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusMessage(); ok {
		_spec.SetField(userprofile.FieldStatusMessage, field.TypeString, value)
	}
	if _u.mutation.StatusMessageCleared() {
		_spec.ClearField(userprofile.FieldStatusMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(userprofile.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(userprofile.FieldTimezone, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
